# Generated by Django 4.2.4 on 2023-11-09 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saludMental', '0004_publicacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicacion',
            options={'verbose_name': 'Publicacion', 'verbose_name_plural': 'Publicaciones'},
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='autor',
        ),
        migrations.AddField(
            model_name='publicacion',
            name='descripcion',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='etiquetas',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterModelTable(
            name='publicacion',
            table='publicacion',
        ),
    ]
