# Generated by Django 4.2.4 on 2023-11-09 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saludMental', '0005_alter_publicacion_options_remove_publicacion_autor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto_de_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfil/'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='creado',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
