# Generated by Django 4.2.4 on 2023-11-09 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saludMental', '0006_usuario_foto_de_perfil_alter_usuario_creado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto_de_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfil/', verbose_name='Foto de Perfil'),
        ),
    ]
